/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyQuanCafe;

import javax.swing.JOptionPane;

/**
 *
 * @author namduong
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuDatMon = new javax.swing.JMenu();
        menuQuanLyMon = new javax.swing.JMenu();
        menuQuanLyKhachHang = new javax.swing.JMenu();
        menuQuanLyNhanVien = new javax.swing.JMenu();
        menuQuanLyKho = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(830, 554));
        setSize(new java.awt.Dimension(830, 554));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Đặt Món");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/namduong/Downloads/2p5mv0.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 510));

        menuDatMon.setText("Đặt Món");
        menuDatMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDatMonMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuDatMon);

        menuQuanLyMon.setText("Quản Lý Món");
        menuQuanLyMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLyMonMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuQuanLyMon);

        menuQuanLyKhachHang.setText("Quản Lý Khách Hàng");
        menuQuanLyKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLyKhachHangMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuQuanLyKhachHang);

        menuQuanLyNhanVien.setText("Quản Lý Nhân Viên");
        menuQuanLyNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLyNhanVienMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuQuanLyNhanVien);

        menuQuanLyKho.setText("Quản Lý Kho");
        menuQuanLyKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLyKhoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuQuanLyKho);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuQuanLyMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyMonMouseClicked
        // TODO add your handling code here:
        new quanLyMon().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuQuanLyMonMouseClicked

    private void menuQuanLyKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyKhachHangMouseClicked
        new quanLyKhachHang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuQuanLyKhachHangMouseClicked

    private void menuQuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyNhanVienMouseClicked
        new quanLyNhanVien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuQuanLyNhanVienMouseClicked

    private void menuQuanLyKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyKhoMouseClicked
        new quanLyKho().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuQuanLyKhoMouseClicked

    private void menuDatMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDatMonMouseClicked
        // TODO add your handling code here:
        new menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuDatMonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuDatMon;
    private javax.swing.JMenu menuQuanLyKhachHang;
    private javax.swing.JMenu menuQuanLyKho;
    private javax.swing.JMenu menuQuanLyMon;
    private javax.swing.JMenu menuQuanLyNhanVien;
    // End of variables declaration//GEN-END:variables
}
