/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyQuanCafe;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author namduong
 */
public class quanLyMon extends javax.swing.JFrame {

    /**
     * Creates new form quanLiKhacHang
     */
    public quanLyMon() {
        initComponents();
        setVisible(true);
        this.taoTable();
    }
    DefaultTableModel tblModelTT;
    public void taoTable() {
        tblModelTT = new DefaultTableModel();
        String tieuDe[] = {"Mã món", "Tên món", "Giá", "Size", "Loại"};
        tblModelTT.setColumnIdentifiers(tieuDe);
        tbMon.setModel(tblModelTT);
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMon = new javax.swing.JTable();
        inputBox = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtMaMon = new javax.swing.JTextField();
        txtTenMon = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        selectSize = new javax.swing.JComboBox<>();
        selectType = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        actionBox = new javax.swing.JPanel();
        themNhanVien = new javax.swing.JButton();
        xoaNhanVien = new javax.swing.JButton();
        suaNhanVien = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuDatMon = new javax.swing.JMenu();
        menuQuanLyMon = new javax.swing.JMenu();
        menuQuanLyKhachHang = new javax.swing.JMenu();
        menuQuanLyNhanVien = new javax.swing.JMenu();
        menuQuanLyKho = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Quản Lý Món");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 70));

        tbMon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã món", "Tên món", "Giá bán", "Size", "Loại"
            }
        ));
        tbMon.setAutoscrolls(false);
        tbMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMon);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 780, 140));

        inputBox.setForeground(new java.awt.Color(255, 255, 255));
        inputBox.setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mã món:");
        jPanel1.add(jLabel2);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tên món:");
        jPanel1.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Giá bán:");
        jPanel1.add(jLabel5);

        inputBox.add(jPanel1);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        txtMaMon.setMinimumSize(new java.awt.Dimension(10, 20));
        txtMaMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaMonActionPerformed(evt);
            }
        });
        jPanel3.add(txtMaMon);

        txtTenMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenMonActionPerformed(evt);
            }
        });
        jPanel3.add(txtTenMon);

        txtGiaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaBanActionPerformed(evt);
            }
        });
        jPanel3.add(txtGiaBan);

        inputBox.add(jPanel3);

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Size:");
        jPanel2.add(jLabel8);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Loại:");
        jPanel2.add(jLabel3);
        jPanel2.add(jPanel6);

        inputBox.add(jPanel2);

        jPanel5.setLayout(new java.awt.GridLayout(0, 1));

        selectSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L" }));
        jPanel5.add(selectSize);

        selectType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cà phê", "Trà", "Bánh", "Thức uống khác" }));
        jPanel5.add(selectType);
        jPanel5.add(jPanel4);

        inputBox.add(jPanel5);

        getContentPane().add(inputBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 780, 130));

        actionBox.setLayout(new java.awt.GridLayout(2, 1));

        themNhanVien.setText("Thêm");
        themNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themNhanVienActionPerformed(evt);
            }
        });
        actionBox.add(themNhanVien);

        xoaNhanVien.setText("Xoá");
        xoaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaNhanVienActionPerformed(evt);
            }
        });
        actionBox.add(xoaNhanVien);

        suaNhanVien.setText("Sửa");
        actionBox.add(suaNhanVien);

        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Reset thông tin đã điền");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        actionBox.add(jButton1);

        getContentPane().add(actionBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 780, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/namduong/Downloads/2p5mv0.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(833, 531));
        jLabel1.setMinimumSize(new java.awt.Dimension(833, 531));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 510));

        menuDatMon.setText("Đặt Món");
        menuDatMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDatMonMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuDatMon);

        menuQuanLyMon.setText("Quản Lý Món");
        menuQuanLyMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLyMonMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuQuanLyMon);

        menuQuanLyKhachHang.setText("Quản Lý Khách Hàng");
        menuQuanLyKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLyKhachHangMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuQuanLyKhachHang);

        menuQuanLyNhanVien.setText("Quản Lý Nhân Viên");
        menuQuanLyNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLyNhanVienMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuQuanLyNhanVien);

        menuQuanLyKho.setText("Quản Lý Kho");
        menuQuanLyKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLyKhoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuQuanLyKho);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMonActionPerformed

    private void txtGiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaBanActionPerformed

    private void txtTenMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenMonActionPerformed

    private void themNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themNhanVienActionPerformed
        String row[] = new String[5];
        row[0] = txtMaMon.getText();
        row[1] = txtTenMon.getText(); 
        row[2] = txtGiaBan.getText();  
        String sizeValue = (String)selectSize.getSelectedItem();
        row[3] = sizeValue;
        String typeValue = (String)selectType.getSelectedItem();
        row[4] = typeValue;
//        if (txtID.getText().equals("") || txtHoVaTen.getText().equals("") || txtTuoi.getText().equals("") || txtDiaChi.getText().equals("") || txtSDT.getText().equals("") || txtEmail.getText().equals("")) {
//            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
//        }
//        else {
            tblModelTT.addRow(row);
            txtMaMon.setText(null);
            txtTenMon.setText(null); 
            txtGiaBan.setText(null);  
            selectSize.setSelectedItem(null);
            selectType.setSelectedItem(null);
//        }
    }//GEN-LAST:event_themNhanVienActionPerformed

    private void xoaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaNhanVienActionPerformed
        int indexTB = tbMon.getSelectedRow();
        tblModelTT.removeRow(indexTB);        // TODO add your handling code here:
    }//GEN-LAST:event_xoaNhanVienActionPerformed

    private void tbMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMonMouseClicked
        
    }//GEN-LAST:event_tbMonMouseClicked

    private void menuDatMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDatMonMouseClicked
        // TODO add your handling code here:
        new menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuDatMonMouseClicked

    private void menuQuanLyMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyMonMouseClicked
        // TODO add your handling code here:
        new quanLyMon().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuQuanLyMonMouseClicked

    private void menuQuanLyKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyKhachHangMouseClicked
        new quanLyKhachHang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuQuanLyKhachHangMouseClicked

    private void menuQuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyNhanVienMouseClicked
        new quanLyNhanVien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuQuanLyNhanVienMouseClicked

    private void menuQuanLyKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyKhoMouseClicked
        new quanLyKho().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuQuanLyKhoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtMaMon.setText(null);
        txtTenMon.setText(null); 
        txtGiaBan.setText(null); 
        selectSize.setSelectedItem(null);
        selectType.setSelectedItem(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanLyMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanLyMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanLyMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanLyMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanLyMon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionBox;
    private javax.swing.JPanel inputBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuDatMon;
    private javax.swing.JMenu menuQuanLyKhachHang;
    private javax.swing.JMenu menuQuanLyKho;
    private javax.swing.JMenu menuQuanLyMon;
    private javax.swing.JMenu menuQuanLyNhanVien;
    private javax.swing.JComboBox<String> selectSize;
    private javax.swing.JComboBox<String> selectType;
    private javax.swing.JButton suaNhanVien;
    private javax.swing.JTable tbMon;
    private javax.swing.JButton themNhanVien;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaMon;
    private javax.swing.JTextField txtTenMon;
    private javax.swing.JButton xoaNhanVien;
    // End of variables declaration//GEN-END:variables
}
